# Generated by Django 5.1.4 on 2025-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_encoded', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('feature_longevity_men', models.BooleanField(default=False)),
                ('feature_longevity_unisex', models.BooleanField(default=False)),
                ('feature_longevity_women', models.BooleanField(default=False)),
                ('feature_occasion_business', models.BooleanField(default=False)),
                ('feature_occasion_daily', models.BooleanField(default=False)),
                ('feature_occasion_evening', models.BooleanField(default=False)),
                ('feature_occasion_leisure', models.BooleanField(default=False)),
                ('feature_occasion_night_out', models.BooleanField(default=False)),
                ('feature_occasion_sports', models.BooleanField(default=False)),
                ('feature_season_fall', models.BooleanField(default=False)),
                ('feature_season_spring', models.BooleanField(default=False)),
                ('feature_season_summer', models.BooleanField(default=False)),
                ('feature_season_winter', models.BooleanField(default=False)),
                ('feature_style_classic', models.BooleanField(default=False)),
                ('feature_style_modern', models.BooleanField(default=False)),
                ('feature_Type_Animalic', models.BooleanField(default=False)),
                ('feature_Type_Aquatic', models.BooleanField(default=False)),
                ('feature_Type_Chypre', models.BooleanField(default=False)),
                ('feature_Type_Citrus', models.BooleanField(default=False)),
                ('feature_Type_Creamy', models.BooleanField(default=False)),
                ('feature_Type_Earthy', models.BooleanField(default=False)),
                ('feature_Type_Floral', models.BooleanField(default=False)),
                ('feature_Type_Fougere', models.BooleanField(default=False)),
                ('feature_Type_Fresh', models.BooleanField(default=False)),
                ('feature_Type_Fruity', models.BooleanField(default=False)),
                ('feature_Type_Gourmand', models.BooleanField(default=False)),
                ('feature_Type_Green', models.BooleanField(default=False)),
                ('feature_Type_Leathery', models.BooleanField(default=False)),
                ('feature_Type_Oriental', models.BooleanField(default=False)),
                ('feature_Type_Powdery', models.BooleanField(default=False)),
                ('feature_Type_Resinous', models.BooleanField(default=False)),
                ('feature_Type_Smoky', models.BooleanField(default=False)),
                ('feature_Type_Spicy', models.BooleanField(default=False)),
                ('feature_Type_Sweet', models.BooleanField(default=False)),
                ('feature_Type_Synthetic', models.BooleanField(default=False)),
                ('feature_Type_Woody', models.BooleanField(default=False)),
            ],
        ),
    ]
